### ?XDEBUG_SESSION_START=PHPSTORM

### Get an entity
GET {{host}}/entity/home
Authorization: bearer {{token}}
Content-Type: application/json





### Get an entity children
GET {{host}}/entity/home/children
Authorization: bearer {{token}}
Content-Type: application/json





### Get an entity with selected fields
GET {{host}}/entity/home?fields=id,e.model,contents.*,user.username&lang=es
Authorization: bearer {{token}}
Content-Type: application/json




### Get an entity with all information
GET {{host}}/entity/53f22c41-05cd-428c-912a-430081c3abd2?select=e.*,contents.*,data.*&relations
Authorization: bearer {{token}}
Content-Type: application/json



### Get an entity seting the language
GET {{host}}/entity/9c58def5-8867-4201-bf0f-86ff04e90bd9?lang=en
Authorization: bearer {{token}}
Content-Type: application/json





### Get an entties with a filter in related model
GET {{host}}/entity/?select=model,entities.parent_id,user.id,user.name&where=user.username:admin
Authorization: bearer {{token}}
Content-Type: application/json





### Get an entties with a filter in entities table
GET {{host}}/entity/?select=id,e.model,contents.title&where=model:medium
Authorization: bearer {{token}}
Content-Type: application/json



### Get an entity, its relations, ancestors (useful for editing)
GET {{host}}/entity/home/forEdit
Authorization: bearer {{token}}
Content-Type: application/json



### Get an entity parent
GET {{host}}/entity/{{entity_id}}/parent
Authorization: bearer {{token}}
Content-Type: application/json





### Get an entity descendants
GET {{host}}/entity/home/descendants?select=id,model,tree.depth&media=icon
Authorization: bearer {{token}}
Content-Type: application/json





### Get an entities related by
GET {{host}}/entity/home/relations/medium?select=id,model
Authorization: bearer {{token}}
Content-Type: application/json





### Get an entities inverse relations
GET {{host}}/entity/home/inverse-relations/ancestor?select=id,model
Authorization: bearer {{token}}
Content-Type: application/json






### Create an entities relations
POST {{host}}/entity/home/relations?select=id,mode
Authorization: bearer {{token}}
Content-Type: application/json

{
  "id": "root",
  "kind": "relation"
}




### Delete a relation
DELETE {{host}}/entity/home/relations/relation/root
Authorization: bearer {{token}}
Content-Type: application/json







### Get an entity ancestors
GET {{host}}/entity/home/ancestors?select=id,model,tree.depth
Authorization: bearer {{token}}
Content-Type: application/json






### Get an entity tree, specify fields, max depth an the order of the entities in each branch
GET {{host}}/entity/root/tree?select=model,c.title&depth=3&order=c.title
Authorization: bearer {{token}}
Content-Type: application/json





### Create an entity
POST {{host}}/entity/
Authorization: bearer {{token}}
Content-Type: application/json

{
  "model": "medium",
  "parent_id": "root",
  "medium": {
    "format": "png",
    "size": 888
  },
  "contents": {
    "title": "Posted media :)",
    "en": {
      "summary": "The summary"
    },
    "es": {
      "summary": "La reseña"
    }
  }
}

> scripts/last-entity-id.js





### Update an entity
PATCH {{host}}/entity/{{entity_id}}
Authorization: bearer {{token}}
Content-Type: application/json

{
  "model": "medium",
  "medium": {
    "format": "png",
    "size": 999
  },
  "contents": {
    "title": "Updated media :)",
    "en": {
      "summary": "The summary 2"
    },
    "es": {
      "summary": "La reseña 3"
    }
  }
}




### Update an entity 2
PATCH {{host}}/entity/home
Authorization: bearer {{token}}
Content-Type: application/json

{
  "unpublicated_at": "2020-12-12 12:12:12"
}




### Move entity from parent

PATCH {{host}}/entity/home?XDEBUG_SESSION_START=PHPSTORM
Authorization: bearer {{token}}
Content-Type: application/json

{
  "parent_id": "media"
}

###
